# Sets tmux to 24bit colour
set-option -sa terminal-overrides ",xterm*:Tc"

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Add mouse support
set -g mouse on

# Set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Plugins to install
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'wfxr/tmux-power'
set -g @plugin 'wfxr/tmux-net-speed'
set -g @plugin "tmux-plugins/tmux-yank"

set -g @tmux_power_theme 'gold'
set -g @tmux_power_left_a '#{USER}@#h'
set -g @tmux_power_left_b '#S'
set -g @tmux_power_left_c '󰕒 #{upload_speed}'
set -g @tmux_power_right_x '󰇚 #{download_speed}'
set -g @tmux_power_right_y '%T'
set -g @tmux_power_right_z '%F'

run '~/.config/tmux/plugins/tpm/tpm'

# Copy mode key bindings
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
